### PR TITLE
Fixes #85 : Diacritics on AE and OE

### LINKED ISSUE #85: missing liturgical latin characters
migration of [SF issue 323](https://sourceforge.net/p/linuxlibertine/bugs/323/): a few characters are missing for the font to be useable  in liturgical latin:

- œ+combining acute
- Œ+combining acute
- œ+combining acute small caps
- ǽ small caps

### PR DESCRIPTION
**Pull request by mgavioli**
Ajusted / added the `top_akzent` anchor in `AE`, `ae.sc`, `ae`, `OE`, `oe.sc`, `oe` glyphs to correctly position diacritics above them.
As in most fonts -- all except Serif Bold-italic and Serif Display -- the glyphs U+01E2 (\*"AEmacron"), U+01E3 (\*"aemacron"), "AEacute" (U+01FC) and "aeacute" (U+01FD) were defined and this prevented proper application of "smcp" and "c2sm" to separately accented glyphs (AE + conbining macron, ...), two additional glyphs ("aeacute.sc" and "uni01E3.sc") have been created in those fonts and relevant entries added to "smcp" and "c2sc".

Fixes https://github.com/khaledhosny/libertinus/issues/85

Summary:

*) Serif regular: AE, ae, OE anchor adjusted; oe, ae.sc, oe.sc anchor added
*) Serif italic: AE, ae, OE anchor adjusted; oe, ae.sc, oe.sc anchor added
*) Serif s.-bold: AE anchor adjusted; ae, OE, oe, ae.sc, oe.sc anchor added
*) Serif s.-bold it.: AE anchor adjusted; ae, OE, oe, ae.sc, oe.sc anchor added
*) Serif bold: AE, OE anchor adjusted; oe, ae.sc, oe.sc anchor added
*) Serif bold it.: O, AE, ae, OE anchor adjusted; oe, ae.sc, oe.sc anchor added; lacks "c2sc" table
*) Serif display: E, AE, ae, OE anchor adjusted; oe anchor added; Display lacks small caps

*) Sans regular: AE, ae, OE anchor adjusted; oe, ae.sc, oe.sc anchor added
*) Sans italic: AE, ae, OE anchor adjusted; oe, ae.sc, oe.sc anchor added
*) Sans bold: AE, ae, OE anchor adjusted; oe, ae.sc, oe.sc anchor added

Sans uses special diacritics for capitals, which are not mapped to Unicode points and cannot be used as separate combining diacritics; the anchor points chosen for AE and OE ensure reasonable results with standard combining diacritics, even if slightly different from other capitals.

LibreOffice screen shot (of some diacritics):

issue_085_screenshot_02

### CODE REVIEW

**Comment by khaledhosny** [comment]
This is now conflicting because I merged #135 first (committing binary files to the repository is coming back and biting me in the rear). Please rebase on master.

**Comment by khaledhosny** [comment]
```
git fetch
git checkout Fix_85_ae_oe_diacritics
git rebase origin/master
make
git add -u
git rebase --continue
```

**Comment by mgavioli** [comment]
I think I got it, but rebasing has been tricky: after the procedure you listed, I had to `touch` the 2 .SFD modified by the other PR and do another `make`, as apparently the changes of this PR relative to those 2 .SFD weren't applied yet at the time of the first `make` in the middle of the rebase (but possibly I did something wrong with `git`: I am unfamiliar with the implications of having results of 'compilation' under version control...).

**Comment by alerque** [comment]
> committing binary files to the repository is coming back and biting me in the rear

It always does ;-)

I was watching your discussion earlier about build tools and while I haven't run it myself it sounds like you have the build system for this turning out repeatable builds across systems. If that's the case it would probably be best to stop updating the binaries and leave that to CI to produce for every commit and use release tags to attached "sanctioned" builds.

**Comment by khaledhosny** [comment]
> I was watching your discussion earlier about build tools and while I haven't run it myself it sounds like you have the build system for this turning out repeatable builds across systems. If that's the case it would probably be best to stop updating the binaries and leave that to CI to produce for every commit and use release tags to attached "sanctioned" builds.

I’m still a bit paranoid and want to have binary files for every commit in master stored somewhere. I’m thinking of doing that in a branch and letting CI builds push to it.

**Comment by khaledhosny** [comment]
> I had to touch the 2 .SFD modified by the other PR and do another make

You can always force remake with `make -B`.

**Pull request merged**
