### PR TITLE
Fix #97 - Eng forms

### LINKED ISSUE #97: Eng looks different in Libertinus Serif
The shape of Latin Eng looks different in Libertinus Serif while switching different font weight and styles.

See: https://sourceforge.net/p/linuxlibertine/bugs/328/

### PR DESCRIPTION
**Pull request by mgavioli**
Fix #97 - Eng forms

Fixes https://github.com/khaledhosny/libertinus/issues/97

Summary.

Eng forms are in Upper Case style in some fonts and in Lower Case style in other.

This PR will make them uniform by using the LC style as primary and the UC style as Sami localised form.

It adds a `locl` lookup table with localised forms for Sami with languages: Finnish, Inari Sami, Lule Sami, Norwegian, Northern Sami, Skolt Sami, Southern Sami, Swedish (but not Kildin Sami, which uses Cyrillic) and adds to this table a substitution sub-table replacing `Eng` with `Eng.UCStyle` and `eng.sc` with `Eng.UCStyle.sc`.

It also adds a `ss07` (the first style not used in any Libertinus font) swapping each eng style with the other.

Details.

**Mono**:
- added English (US) names to the stylistic sets (`ss01` to `ss03`; `ss02` and `ss03` are empty)
- added 1 encoding slot for `Eng.UCStyle` (Display has no small caps)
- `Eng.UCStyle`: added UC form

**Sans Regular**:
- added English (US) names to the stylistic sets (`ss01` to `ss04`)
- `Eng`: replaced UC form with LC form
- `eng.sc`: replaced small capital UC form with small capital LC form
- added 2 encoding slots for `Eng.UCStyle` and `Eng.UCStyle.sc`
- `Eng.UCStyle`: added UC form (copied from original `Eng` shape)
- `Eng.UCStyle.sc`: added small capital UC form (copied from original `eng.sc` form)

**Sans Italic**:
- added English (US) names to the stylistic sets (`ss01` to `ss04`)
- `Eng`: replaced UC form with LC form
- `eng.sc`: replaced small capital UC form with small capital LC form
- added 2 encoding slots for `Eng.UCStyle` and `Eng.UCStyle.sc`
- `Eng.UCStyle`: added UC form (copied from original `Eng` shape)
- `Eng.UCStyle.sc`: added small capital UC form (copied from original `eng.sc` form)

**Sans Bold**:
- added English (US) names to the stylistic sets (`ss01`, `ss03` and `ss05`)
- `Eng`: replaced UC form with LC form
- `eng.sc`: replaced small capital UC form with small capital LC form
- added 2 encoding slots for `Eng.UCStyle` and `Eng.UCStyle.sc`
- `Eng.UCStyle`: added UC form (copied from original `Eng` shape)
- `Eng.UCStyle.sc`: added small capital UC form (copied from original `eng.sc` form)

**Serif Display**:
- added English (US) names to the stylistic sets (`ss01` to `ss06`)
- added 1 encoding slot for `Eng.UCStyle` (Display has no small caps)
- `Eng.UCStyle`: added UC form

**Serif Regular**:
- added English (US) names to the stylistic sets (`ss01` to `ss06`)
- `eng.sc`: replaced small capital UC form with small capital LC form
- added 2 encoding slots for `Eng.UCStyle` and `Eng.UCStyle.sc`
- `Eng.UCStyle`: added UC form
- `Eng.UCStyle.sc`: added small capital UC form

**Serif Italic**:
- added English (US) names to the stylistic sets (`ss01` to `ss03`)
- `Eng`: replaced UC form with LC form
- `eng`: cleaned and re-spaced
- `eng.sc`: replaced small capital UC form with small capital LC form
- added 2 encoding slots for `Eng.UCStyle` and `Eng.UCStyle.sc`
- `Eng.UCStyle`: added UC form (copied from original `Eng` shape)
- `Eng.UCStyle.sc`: added small capital UC form (copied from original `eng.sc` form)

**Serif Semi-bold**:
- added English (US) names to the stylistic sets (`ss01` and `ss03`)
- `Eng`: replaced UC form with LC form
- `eng`: cleaned and re-spaced
- `eng.sc`: replaced small capital UC form with small capital LC form
- added 2 encoding slots for `Eng.UCStyle` and `Eng.UCStyle.sc`
- `Eng.UCStyle`: added UC form (copied from original `Eng` shape)
- `Eng.UCStyle.sc`: added small capital UC form (copied from original `eng.sc` form)

**Serif Semi-bold italic**:
- `Eng`: replaced UC form with LC form
- 'eng': corrected and cleaned
- `eng.sc`: replaced small capital UC form with small capital LC form
- added 2 encoding slots for `Eng.UCStyle` and `Eng.UCStyle.sc`
- `Eng.UCStyle`: added UC form (copied from original `Eng` shape)
- `Eng.UCStyle.sc`: added small capital UC form (copied from original `eng.sc` form)

**Serif Bold**:
- added English (US) names to the stylistic sets (`ss01` and `ss03`)
- `Eng`: cleaned and re-spaced existing LC form
- `eng`: cleaned and re-spaced
- `eng.sc`: replaced small capital UC form with small capital LC form
- `Eng.UCStyle`: added UC form
- `Eng.UCStyle.sc`: added small capital UC form (copied from original `eng.sc` form)

**Serif Bold italic**:
- `Eng`: cleaned and re-spaced existing LC form
- `eng`: cleaned and re-spaced
- `eng.sc`: replaced small capital UC form with small capital LC form
- `Eng.UCStyle`: added UC form
- `Eng.UCStyle.sc`: added small capital UC form (copied from original `eng.sc` form)

Screen shots:
Default, with Lower Case style Ŋ (note that Display is missing one character):

issue_097_screenshot_04_a

Setting one of the languages for which Upper Case style localisation is enabled (here Norwegian, as LibreOffice didn't allow me to set any Sami language):

issue_097_screenshot_04_b

### CODE REVIEW

**Comment by mgavioli** [comment]
Travis failure is expected for the time being, as the Sans Regular .sfd source is still worked upon.

The Seeif Regular font should be usable, though.

**Comment by mgavioli** [comment]
It is probably useful to have a way to access the 'other' shape, whatever the default is for the current locale. `salt`?

**Comment by khaledhosny** [comment]
Stylistic set would be better IMO.

>

**Comment by mgavioli** [comment]
The problem I have with `ss..` is that I (and possibly others as well) never remember which set does what and they change from font to font. For Libertinus, stylistic sets are currently not documented anywhere (Serif regular has 6 of them) and, even adding a specific documentation, the user needs to have it at hand to use them.

So, just a practical concern but, if stylistic sets are the 'right' way, OK then.

**Comment by khaledhosny** [comment]
But then `salt` becomes a mixed bag of unrelated stuff. Stylistic sets can have user-visible names (Element → Font Info → StyleSet Names). Not all applications show them yet, but at least they can serve as a kind of internal documentation. I think Linux Libertine had user documentation in German, may be we should find it and see if there are any interesting bits and make a new English user documentation based on that (I don’t know German, so I have no collection about its actual content).

**Comment by nsemrau** [comment]
As a native speaker of German, I am willing to volunteer to translate the upstream documentation if the need arises.

**Comment by mgavioli** [comment]
Current status (Serif regular, italic, bold and bold italic, with `locl` but not `ss..` yet):

issue_097_screenshot_02

(I didn't find Sami words with initial Ŋ ! Maybe in Sami it cannot be initial, who knows...)

**Comment by moyogo** [comment]
The only Sami words I have found with Eng are in all-caps. There doesn't seem to be Sami words starting with Eng nor eng.

**Pull request merged**
