### PR TITLE
Fixes #70 G + tilde

### LINKED ISSUE #70: G + Tilde are wrongly placed in some faces
They are used in Guarani texts.

### PR DESCRIPTION
**Pull request by mgavioli**
Rationale: the relevant anchor point for `G`, `g` and/or `tildecomb` have been adjusted. In the majority of cases, the `tildecomb` glyph already had a `top_punkt` anchor; when it lacked any suitable anchor, a `top_punkt` anchor has been added; for Serif Display, the `top_akzent` was present and not far off and has been adjusted.

Fixes https://github.com/khaledhosny/libertinus/issues/70

Summary:

Sans Regular:
- `G`: adjusted `top_punkt` anchor;
- `g`: adjusted `top_punkt` anchor;
- `tildecomb`: added suitable `top_punkt` anchor.

Sans Italic:
- `tildecomb`: added suitable `top_punkt` anchor.

Sans Bold:
- `G`: adjusted `top_punkt` anchor;
- `g`: adjusted `top_punkt` anchor;
- `tildecomb`: adjusted `top_punkt` anchor.

Serif Display:
- `G`: adjusted `top_akzent` anchor.

Serif Semi-bold::
- `G`: adjusted `top_punkt` anchor;
- `g`: adjusted `top_punkt` anchor.

Serif Semi-bold Italic:
- added new anchor class `top_punkt`;
- `G`: added suitable `top_punkt` anchor;
- `g`: added suitable `top_punkt` anchor;
- `tildecomb`: replaced `top_akzent` anchor with suitable `top_punkt` anchor.

Serif Bold Italic:
- added new anchor class `top_punkt`;
- `G`: added suitable `top_punkt` anchor;
- `g`: added suitable `top_punkt` anchor;
- `tildecomb`: added suitable `top_punkt` anchor.

LibreOffice screen shot:

issue_070_screenshot_01

### CODE REVIEW

**Comment by mgavioli** [comment]
> The accent on Sans regular and italic looks off, is this intended?

Well, not really. Placement of the same diacritic is not very consistent across different base glyphs and on the same base across fonts. In part, I tried to compromise between the various (pre-composed) VOWEL + TILDE; in part I was afraid to go to high and risk some clipping.

But you are right, in the Sans, I was too conservative. This is the status after some more adjustments:

issue_070_screenshot_02

`g` + `~` in Serif Bold is still a bit low, but it was already in place (I didn't touch at that font), and it uses for the tilde the same anchor (`top_akzent`) of many other diacritics; changing it may trigger a 'snow ball' effect... As it is not so far off, I preferred to leave it as it is.

**Comment by mgavioli** [comment]
Incidentally: my (local) git shows as not merged all my branches actually merged in github; for instance:

- https://github.com/khaledhosny/libertinus/pull/134
- https://github.com/khaledhosny/libertinus/pull/135
- https://github.com/khaledhosny/libertinus/pull/136

My local master, origin master and upstream master are all in synch and the relevant commits are in them. Might it be something I did or did you actually modified them before merging? Thanks.

**Comment by khaledhosny** [comment]
> Incidentally: my (local) git shows as not merged all my branches actually merged in github; for instance:
That is because I use “Rebase and merge” on GitHub (because I don’t like merge commits), which changes commit ids, GitHub should have been smart enough not to change commit ids if the branch is already on top of master!

**Comment by alerque** [comment]
@khaledhosny Fairly recently I noticed that if a PR has a single commit that is already on top of master and you merge it, it will not produce a merge commit on Github. I don't know if this is a setting somewhere that I selected, but I agree it's nice to avoid merge commits when a branch is just one commit and not actually a divergent branch. Otherwise Github is just following what `git rebase` does, and it generates new IDs because some of the meta data being checksumed does change.

**Comment by khaledhosny** [comment]
I think what I need is a “Use `git merge` if it does not produce a merge commit, otherwise use `git rebase` option”, but I guess I can try doing this locally instead of using GitHub UI.

**Pull request merged**
