### PR TITLE
Issue 118 aring macron stacking

### PR DESCRIPTION
**Pull request by mgavioli**
Fixed by adjusting the "top_akzent" anchor in either (or both) the aring or/and the uni0304 (COMBINING MACRON) glyphs

In most fonts, the "top_akzent" anchor of the uni0305 (COMBINING OVERLINE) glyph has been adjusted too, to improve consistency.

Summary:
*) **bold**: adjusted aring and uni0305 anchors
*) **bolditalic**: added aring and uni0304 anchors and adjusted uni0305 anchor
*) **italic**: added aring anchor
*) **regular**: adjusted aring and uni0305 anchors
*) **semibold**: added aring anchor; removed "top_punkt" anchor and added "top_akzent": it seems they cannot coexist; this affected some Cyrillic characters, apparently without side effects: checks welcome!
*) **semibolditalic**: adjusted aring and uni0305 anchors
*) **display-regular**: adjusted aring and uni0305 anchors

A sample via LibreOffice (first line 48pt, other lines 12pt; at 200% zoom):

issue_118_screenshot_01

I have generated the .OTF (with `make`), but I left them in a separate commit, just in case. The change from `tools/sfdclean.sh` to the new `tools/sfdnormalize.py` got me 'in between' and I preferred to adjust manually the only odd .SFD file.

Please advise if you prefer the PR squashed into a single commit.

Fixes https://github.com/khaledhosny/libertinus/issues/118

### CODE REVIEW

**Comment by khaledhosny** [comment]
Thanks for the great work!

Yes, please squash the commits.

For the commit message, I prefer to skip the issue number in the summary line and instead add a `Fixes https://github.com/khaledhosny/libertinus/issues/118` line at end if the commit fixes the issue completely, or `Part of https://github.com/khaledhosny/libertinus/issues/118` if some work is remaining (I prefer full issue URLs so that I can easily open the issue anywhere).

**Comment by KrasnayaPloshchad** [comment]
Can you also fix #67?

**Comment by mgavioli** [comment]
@khaledhosny : ok, I'll wait a couple of days for the issue proponent to check the output and I'll squash the commits if no more work is needed.

@KrasnayaPloshchad : I'll try; issue https://github.com/khaledhosny/libertinus/issues/67 seems tougher, though, as it involves lots of diacritics.

**Comment by dajare** [comment]
This is brilliant! Thanks so much, @mgavioli -- this was the only "stacking" issue I encountered my work. The bug looks well and truly squashed. 👍

**Comment by mgavioli** [comment]
@dajare : thanks!
@khaledhosny : commits squashed.

**Comment by khaledhosny** [comment]
Thanks!

**Comment by KrasnayaPloshchad** [comment]
> Can you also fix #67?

No fix for that.

**Comment by mgavioli** [comment]
> No fix for that.

I'll come to #67 too. I only have that much free time to spend on this topics and I spent most of this week laying with 40 °C (104 °F) of fewer...

**Pull request merged**
