### PR TITLE
Fix #113 - Service Mark and Trade Mark in Sans

### LINKED ISSUE #113: Service Mark and Trade Mark Sign has wrong from in Libertinus Sans
Service Mark (U+2120) and Trade Mark Sign (U+2122) appear to be adapted from the serif face in Libertinus Sans.

See: #112

### PR DESCRIPTION
**Pull request by mgavioli**
Fixes https://github.com/khaledhosny/libertinus/issues/113

In the three Sans fonts, the Service Mark (U+2120) and Trade Mark glyphs (U+2122) were not in the same style of the font and not sans at all.

They have been re-done using references to the main Latin 'M', 'S' and 'T' glyphs scaled to 54%. Spacing has also been revised, generally increased.

### CODE REVIEW

**Comment by khaledhosny** [comment]
For small marks like these, wouldn’t it be better if they were emboldened a bit, no not look washed up next to normal sized glyphs? Can you attach before and after screenshots (and may be the serif too, for comparison)?

**Comment by mgavioli** [comment]
Some screen shots from LibreOffice. I made two variants, one simply scaled and one scaled and then emboldened (approx. 1/3 of stem and bar widths).

**Original situation** (before any change):
issue_113_screenshot_original

**Scaled references**:
issue_113_screenshot_scaled

**Scaled and emboldened**:
issue_113_screenshot_scaled_embold

**Serif** (for comparison):
issue_113_screenshot_serif

Notes:
- in the Serif bold, `TM` and `SM` are not emboldened.
- in the Sans (italic and bold), there seems to be a spacing issue in the `tsiv` sequence.

**Comment by khaledhosny** [comment]
Scaled and emboldened version looks better IMO, the scaled-only version looks too light.

**Comment by nsemrau** [comment]
Subtly bolder super- and subscript characters seem to be a hallmark of high-quality typography (see e.g. [1 (caption of first image)](https://en.wikipedia.org/wiki/Subscript_and_superscript), [2]( https://www.fonts.com/content/learning/fontology/level-3/numbers/superior-and-inferior-figures)), so I vote for the emboldend version, too.

BTW: Due to the argument that slightly bigger is (percieved as) higher quality, I would also love to see a return of the alternative figures in issue #40 in the long run. :)

**Comment by mgavioli** [comment]
Bolder version pushed.

I hope not to have messed things up squashing the commits of the two versions...

**Comment by khaledhosny** [comment]
Thanks!

**Pull request merged**
