### PR TITLE
Fixes #119: Add Bitcoin sign to Sans

### LINKED ISSUE #119: Support Bitcoin sign
It would be awesome if you add support for Bitcoin (₿) sign.

### PR DESCRIPTION
**Pull request by mgavioli**
fixes https://github.com/khaledhosny/libertinus/issues/119

Sample (regular, italic, bold):

issue_119_screenshot_01

### CODE REVIEW

**Comment by mgavioli** [comment]
@khaledhosny : I tried `sfdnormalize.py` and it generated some many modifications to the .SFD that I did not even attempt to understand them. So, I cleaned the 3 .SFD involved by this PR by hand.

FYI, I am attaching a ZIP with `libertinussans-regular_prenormalized.sfd` (the same as the `libertinussans-regular.sfd` of this PR, i.e. after manual cleaning) and `libertinussans-regular_postnormalized.sfd` (after running `sfdnormalize.py` on the former): the diff between them should nothing (or almost nothing) but it is about 100,000 lines long! Maybe your results will be different.

[sdfnormalize_test.zip](https://github.com/khaledhosny/libertinus/files/1738515/sdfnormalize_test.zip)

**Comment by khaledhosny** [comment]
Can you please revert the changes to the unrelated OTF files (the non-sans ones)?

The `sfdnormalize.py` issue is odd, I tried locally on the prenormalized and it made no changes as expected, are you using Python 2?

OK, I tested with Python 2 and it gave me results like yours, looks like I broke something while porting to Python 3. In the meantime you can use it with Python 3 and I’ll see if I can debug the Python 2 issue.

**Comment by mgavioli** [comment]
Ok, I'll revert the unchanged OTF's (later this night) and I'll use python3 for `sfdnormalize.py`

**Comment by khaledhosny** [comment]
If you rebase on master, it should work with Python 2 as well now. You can now also do `make normalize` and I added some simple Travis CI support.

**Comment by khaledhosny** [comment]
Also I think the commit message should match one of the documented keywords [here](https://help.github.com/articles/closing-issues-using-keywords/) for GitHub to auto-close the issue once the commit is merged.

**Comment by mgavioli** [comment]
I think I got everything in place eventually:

- reverted unaffected .OTF
- `make normalize` did work as expected;
- `make` generated the .OTF with no difference from master for the files not affected by this PR, so the latest tweaking seems to do its duty!
- PR description / commit msg updated.

Thanks for your patience!

**Pull request merged**
